### PR TITLE
make enclosure return error on parsing 'none' value

### PR DESCRIPTION
**Pull request by Vvasconcelos**
Sorry about the last pull request got some troubles on my git.

check if that was what you were meaning, I've got a little confuse about that answer.

Thanks!

### CODE REVIEW

**Comment by SlyMarbo** [comment]
This is definitely moving in a good direction. At the moment, if there is an error, we just return the error and no data. As some people will want to ignore the error, I think it would be better if we return the data _and_ the error. That way, people can choose to ignore the error or not.

**Comment by lutzhorn** [comment]
The `lenght` attribute of `enclosure` must be a positive integer for the RSS 2.0 feed to be valid. I've made up a feed that has `length="none"` and it fails to validate: http://www.feedvalidator.org/check.cgi?url=https%3A%2F%2Fwww.lhorn.de%2Ffeed%2Ffefe.enclosure.rss.xml

So I am not sure if the library should fix invalid feeds. Maybe we should think about a 'strict' vs. a 'relaxed' mode: In strict mode only valid feeds are parsed without errors. In relaxed mode invalid feeds throw an error. What do you think?

**Comment by Vvasconcelos** [comment]
I think its a nice idea but, if the library starts to correct every single invalid feeds it will start to be a Frankenstein code.

that just my point of view.

**Comment by lutzhorn** [comment]
I agree. That's why I'd tend to be more strict and let the parsing of an item with `<enclosure length="none" .../>` fail.

But this is a design question. Is there a general pattern how invalid feeds are dealt with?

**Comment by Vvasconcelos** [comment]
I think it's simple, let them just fail. if they're invalid...

I know in most cases who's using the library is not the maintainer of the feed, but make an library go rogue like that, is just not right...

Again, my point of view

**Comment by lutzhorn** [comment]
@SlyMarbo What do you think? What was your approach so far in dealing with invalid feeds?

**Comment by SlyMarbo** [comment]
So far I've generally erred on the side of correctness. I could go either
way here but I think rejecting invalid feeds is probably for the best.

**Pull request closed without merging**
