### PR TITLE
Support humanize enclousure length

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by SlyMarbo** [comment]
Hi @LinuxSuRen. Thanks for your contribution, I really appreciate it. Do you have any data on how widespread 'humanized' enclosure lengths are? [The spec](https://validator.w3.org/feed/docs/rss2.html#ltenclosuregtSubelementOfLtitemgt) gives the length as a simple number, so I'm reluctant to accept other formats unless they are widespread. If there's only one source that gives this format, would it be possible to request the source use the correct format instead?

**Comment by LinuxSuRen** [comment]
hi @SlyMarbo , thanks for your quick response.

I am not familiar with the spec of RSS. Thanks for giving the link. I'm not sure if the humanized enclosure length is common. I'll try to contact the author. This is [the place](https://github.com/LinuxSuRen/goplay/blob/84de8617cecf91278f9569428bcf8070cbb4253d/pkg/data/subscription.yaml#L16) where my project tried to read it.

By the way, I try to [cache the RSS data into a local file](https://github.com/LinuxSuRen/goplay/blob/84de8617cecf91278f9569428bcf8070cbb4253d/pkg/rss/repo.go#L46) in my project (a CLI for podcast). Do you have any suggestions about the below changes?

https://github.com/SlyMarbo/rss/pull/76/files#diff-dacaf1fe7cb0b1b5d8877efa60fab9a9927d3d71f4219815e6f16c6c0ce7e877R35

**Comment by SlyMarbo** [comment]
Hi @LinuxSuRen. Could you achieve the same result by fetching the feed directly (using `http.Get(rssURL)`), then caching the data before calling `rss.Parse(data)`? I'm slightly reluctant to store the raw data in the feed object, as it will increase memory usage considerably.

**Comment by LinuxSuRen** [comment]
hi @SlyMarbo thanks for your suggestion. It's great!

**Comment by LinuxSuRen** [comment]
I'm going to close this PR until I have a better idea.

**Pull request closed without merging**
